# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BatchRenderUI.ui'
#
# Created: Wed Dec  1 16:29:55 2010
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainDialog(object):
    def setupUi(self, mainDialog):
        mainDialog.setObjectName(_fromUtf8("mainDialog"))
        mainDialog.setEnabled(True)
        mainDialog.resize(799, 484)
        self.gridLayout = QtGui.QGridLayout(mainDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.m_fileName = QtGui.QLineEdit(mainDialog)
        self.m_fileName.setEnabled(False)
        self.m_fileName.setObjectName(_fromUtf8("m_fileName"))
        self.gridLayout.addWidget(self.m_fileName, 0, 0, 1, 1)
        self.m_chooseFile = QtGui.QPushButton(mainDialog)
        self.m_chooseFile.setEnabled(True)
        self.m_chooseFile.setObjectName(_fromUtf8("m_chooseFile"))
        self.gridLayout.addWidget(self.m_chooseFile, 0, 1, 1, 1)
        self.s_renderControlGroupBox = QtGui.QGroupBox(mainDialog)
        self.s_renderControlGroupBox.setEnabled(True)
        self.s_renderControlGroupBox.setObjectName(_fromUtf8("s_renderControlGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.s_renderControlGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.s_gridLayoutGroupBox = QtGui.QGridLayout()
        self.s_gridLayoutGroupBox.setObjectName(_fromUtf8("s_gridLayoutGroupBox"))
        self.m_startFrame = QtGui.QSpinBox(self.s_renderControlGroupBox)
        self.m_startFrame.setEnabled(True)
        self.m_startFrame.setMaximum(99999)
        self.m_startFrame.setObjectName(_fromUtf8("m_startFrame"))
        self.s_gridLayoutGroupBox.addWidget(self.m_startFrame, 0, 1, 1, 1)
        self.s_byFrame = QtGui.QLabel(self.s_renderControlGroupBox)
        self.s_byFrame.setEnabled(True)
        self.s_byFrame.setObjectName(_fromUtf8("s_byFrame"))
        self.s_gridLayoutGroupBox.addWidget(self.s_byFrame, 0, 4, 1, 1)
        self.s_endFrame = QtGui.QLabel(self.s_renderControlGroupBox)
        self.s_endFrame.setEnabled(True)
        self.s_endFrame.setObjectName(_fromUtf8("s_endFrame"))
        self.s_gridLayoutGroupBox.addWidget(self.s_endFrame, 0, 2, 1, 1)
        self.m_endFrame = QtGui.QSpinBox(self.s_renderControlGroupBox)
        self.m_endFrame.setEnabled(True)
        self.m_endFrame.setMaximum(999999)
        self.m_endFrame.setProperty(_fromUtf8("value"), 1)
        self.m_endFrame.setObjectName(_fromUtf8("m_endFrame"))
        self.s_gridLayoutGroupBox.addWidget(self.m_endFrame, 0, 3, 1, 1)
        self.s_startFrame = QtGui.QLabel(self.s_renderControlGroupBox)
        self.s_startFrame.setEnabled(True)
        self.s_startFrame.setObjectName(_fromUtf8("s_startFrame"))
        self.s_gridLayoutGroupBox.addWidget(self.s_startFrame, 0, 0, 1, 1)
        self.s_renderLabel = QtGui.QLabel(self.s_renderControlGroupBox)
        self.s_renderLabel.setEnabled(True)
        self.s_renderLabel.setObjectName(_fromUtf8("s_renderLabel"))
        self.s_gridLayoutGroupBox.addWidget(self.s_renderLabel, 1, 0, 1, 1)
        self.m_byFrame = QtGui.QSpinBox(self.s_renderControlGroupBox)
        self.m_byFrame.setEnabled(True)
        self.m_byFrame.setMaximum(200)
        self.m_byFrame.setProperty(_fromUtf8("value"), 1)
        self.m_byFrame.setObjectName(_fromUtf8("m_byFrame"))
        self.s_gridLayoutGroupBox.addWidget(self.m_byFrame, 0, 5, 1, 1)
        self.s_pad = QtGui.QLabel(self.s_renderControlGroupBox)
        self.s_pad.setEnabled(True)
        self.s_pad.setObjectName(_fromUtf8("s_pad"))
        self.s_gridLayoutGroupBox.addWidget(self.s_pad, 0, 6, 1, 1)
        self.m_pad = QtGui.QSpinBox(self.s_renderControlGroupBox)
        self.m_pad.setEnabled(True)
        self.m_pad.setMaximum(10)
        self.m_pad.setObjectName(_fromUtf8("m_pad"))
        self.s_gridLayoutGroupBox.addWidget(self.m_pad, 0, 7, 1, 1)
        self.m_renderer = QtGui.QComboBox(self.s_renderControlGroupBox)
        self.m_renderer.setEnabled(True)
        self.m_renderer.setObjectName(_fromUtf8("m_renderer"))
        self.m_renderer.addItem(_fromUtf8(""))
        self.m_renderer.addItem(_fromUtf8(""))
        self.m_renderer.addItem(_fromUtf8(""))
        self.m_renderer.addItem(_fromUtf8(""))
        self.m_renderer.addItem(_fromUtf8(""))
        self.m_renderer.addItem(_fromUtf8(""))
        self.s_gridLayoutGroupBox.addWidget(self.m_renderer, 1, 1, 1, 2)
        self.s_filename = QtGui.QLabel(self.s_renderControlGroupBox)
        self.s_filename.setEnabled(True)
        self.s_filename.setObjectName(_fromUtf8("s_filename"))
        self.s_gridLayoutGroupBox.addWidget(self.s_filename, 1, 3, 1, 1)
        self.m_outputFileName = QtGui.QLineEdit(self.s_renderControlGroupBox)
        self.m_outputFileName.setEnabled(True)
        self.m_outputFileName.setObjectName(_fromUtf8("m_outputFileName"))
        self.s_gridLayoutGroupBox.addWidget(self.m_outputFileName, 1, 4, 1, 3)
        self.m_extension = QtGui.QComboBox(self.s_renderControlGroupBox)
        self.m_extension.setEnabled(True)
        self.m_extension.setObjectName(_fromUtf8("m_extension"))
        self.m_extension.addItem(_fromUtf8(""))
        self.m_extension.setItemText(0, _fromUtf8(""))
        self.m_extension.addItem(_fromUtf8(""))
        self.m_extension.addItem(_fromUtf8(""))
        self.m_extension.addItem(_fromUtf8(""))
        self.s_gridLayoutGroupBox.addWidget(self.m_extension, 1, 7, 1, 1)
        self.m_outputWindow = QtGui.QTextEdit(self.s_renderControlGroupBox)
        self.m_outputWindow.setEnabled(True)
        self.m_outputWindow.setReadOnly(True)
        self.m_outputWindow.setObjectName(_fromUtf8("m_outputWindow"))
        self.s_gridLayoutGroupBox.addWidget(self.m_outputWindow, 2, 0, 1, 8)
        self.gridLayout_3.addLayout(self.s_gridLayoutGroupBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.s_renderControlGroupBox, 4, 0, 1, 2)
        self.m_chooseProject = QtGui.QPushButton(mainDialog)
        self.m_chooseProject.setEnabled(True)
        self.m_chooseProject.setObjectName(_fromUtf8("m_chooseProject"))
        self.gridLayout.addWidget(self.m_chooseProject, 1, 1, 1, 1)
        self.m_projectDir = QtGui.QLineEdit(mainDialog)
        self.m_projectDir.setEnabled(False)
        self.m_projectDir.setObjectName(_fromUtf8("m_projectDir"))
        self.gridLayout.addWidget(self.m_projectDir, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.m_batchRender = QtGui.QPushButton(mainDialog)
        self.m_batchRender.setEnabled(True)
        self.m_batchRender.setObjectName(_fromUtf8("m_batchRender"))
        self.gridLayout.addWidget(self.m_batchRender, 7, 1, 1, 1)
        self.m_outputDir = QtGui.QLineEdit(mainDialog)
        self.m_outputDir.setEnabled(False)
        self.m_outputDir.setObjectName(_fromUtf8("m_outputDir"))
        self.gridLayout.addWidget(self.m_outputDir, 2, 0, 1, 1)
        self.m_chooseOutputDir = QtGui.QPushButton(mainDialog)
        self.m_chooseOutputDir.setEnabled(True)
        self.m_chooseOutputDir.setObjectName(_fromUtf8("m_chooseOutputDir"))
        self.gridLayout.addWidget(self.m_chooseOutputDir, 2, 1, 1, 1)

        self.retranslateUi(mainDialog)
        QtCore.QMetaObject.connectSlotsByName(mainDialog)

    def retranslateUi(self, mainDialog):
        mainDialog.setWindowTitle(QtGui.QApplication.translate("mainDialog", "Maya Batch Render GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.m_chooseFile.setText(QtGui.QApplication.translate("mainDialog", "Choose File", None, QtGui.QApplication.UnicodeUTF8))
        self.s_renderControlGroupBox.setTitle(QtGui.QApplication.translate("mainDialog", "Render Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.s_byFrame.setText(QtGui.QApplication.translate("mainDialog", "by Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.s_endFrame.setText(QtGui.QApplication.translate("mainDialog", "End Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.s_startFrame.setText(QtGui.QApplication.translate("mainDialog", "Start Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.s_renderLabel.setText(QtGui.QApplication.translate("mainDialog", "Renderer", None, QtGui.QApplication.UnicodeUTF8))
        self.s_pad.setText(QtGui.QApplication.translate("mainDialog", "Pad", None, QtGui.QApplication.UnicodeUTF8))
        self.m_renderer.setItemText(0, QtGui.QApplication.translate("mainDialog", "default", None, QtGui.QApplication.UnicodeUTF8))
        self.m_renderer.setItemText(1, QtGui.QApplication.translate("mainDialog", "mental ray", None, QtGui.QApplication.UnicodeUTF8))
        self.m_renderer.setItemText(2, QtGui.QApplication.translate("mainDialog", "Use Render Globals", None, QtGui.QApplication.UnicodeUTF8))
        self.m_renderer.setItemText(3, QtGui.QApplication.translate("mainDialog", "Hardware", None, QtGui.QApplication.UnicodeUTF8))
        self.m_renderer.setItemText(4, QtGui.QApplication.translate("mainDialog", "Renderman", None, QtGui.QApplication.UnicodeUTF8))
        self.m_renderer.setItemText(5, QtGui.QApplication.translate("mainDialog", "Software", None, QtGui.QApplication.UnicodeUTF8))
        self.s_filename.setText(QtGui.QApplication.translate("mainDialog", "Output filename", None, QtGui.QApplication.UnicodeUTF8))
        self.m_extension.setItemText(1, QtGui.QApplication.translate("mainDialog", "tiff", None, QtGui.QApplication.UnicodeUTF8))
        self.m_extension.setItemText(2, QtGui.QApplication.translate("mainDialog", "exr", None, QtGui.QApplication.UnicodeUTF8))
        self.m_extension.setItemText(3, QtGui.QApplication.translate("mainDialog", "iff", None, QtGui.QApplication.UnicodeUTF8))
        self.m_chooseProject.setText(QtGui.QApplication.translate("mainDialog", "Choose Proj", None, QtGui.QApplication.UnicodeUTF8))
        self.m_batchRender.setText(QtGui.QApplication.translate("mainDialog", "Batch Render", None, QtGui.QApplication.UnicodeUTF8))
        self.m_chooseOutputDir.setText(QtGui.QApplication.translate("mainDialog", "Choose Output Dir", None, QtGui.QApplication.UnicodeUTF8))

